server:
  port: 8080
  servlet:
    context-path: /api/platform

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db-server:3306/wecube_core_04?characterEncoding=utf8&serverTimezone=UTC
#    username: db-user
#    password: db-password

  banner:
    location: classpath:/banner.txt

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      naming:
         physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

camunda:
   bpm:
      enabled: true
      application:
         delete-upon-undeploy: false
         scan-for-process-definitions: false
         deploy-changed-only: true
         resume-previous-versions: true
         resume-previous-by: a value
      history-level: full
      database:
         schema-update: true
       
      admin-user:
         id: demo
         password: demo
         first-name: Kermit
      filter:
         create: All tasks
      job-execution:
         enabled: true
      auto-deployment-enabled: true
      generate-unique-process-application-name: true
      generate-unique-process-engine-name: true

wecube:
  core:
    security-enabled: true
    
    #Authentication provider options: local or CAS. Effective ONLY when security-enabled set as true.
    authentication-provider: local
    #Effective ONLY when security-enabled set as true and authentication-provider turns to CAS
    cas-server-url: http://cas-server-ip:8080/cas
    cas-redirect-app-addr: localhost:8080
    
    cmdb-server-url: http://cmdb-server-ip:37000/cmdb
    max-file-size: 64KB
    httpclient:
      max-total-connections: 200

    plugin:
      plugin-deploy-path: /opt
      plugin-package-bucket-name: wecube-plugin-package-bucket
      register-file: register.xml
      image-file: image.tar
      ui-file: ui.zip
      init-db-sql: init.sql
      upgrade-db-sql: upgrade.sql
      plugin-package-name-of-deploy: deployment-plugin-name
      static-resource-server-ip: 192.168.0.17
      static-resource-server-user: root
      static-resource-server-password: password
      static-resource-server-port: 22
      static-resource-server-path: /root/app/ui-resources

    s3:
      endpoint: http://s3-server:9000
      access-key: access_key
      secret-key: secret_key

    cmdb-data:
      enum-category-type-system: 1
      enum-category-type-common: 2
      enum-category-ci-type-layer: ci_layer
      enum-category-ci-type-catalog: ci_catalog
      enum-category-ci-type-zoom-levels: ci_zoom_level

      business-key-attribute-name: biz_key
      status-attribute-name: state

    resource:
      dockerPullImageTimeout: 300
      passwordEncryptionSeed: defaultSeed
