server:
  port: 18080
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://uat-db-server:3306/wecube_core_04?characterEncoding=utf8&serverTimezone=UTC
    username: db-user
    ***REMOVED***

wecube:
  core:
    cas-server-url: http://uat-cas-server:8080/cas
    cmdb-server-url: http://uat-cmdb-server-ip:37000/cmdb
    plugin:
      plugin-hosts: 192.168.0.1, 192.168.0.2
      plugin-package-name-of-deploy: deployment-plugin-name

    s3:
      endpoint: http://uat-s3-server:9000
      access-key: access_key
      secret-key: secret_key
