server:
  port: 8080
  servlet:
    context-path: /platform
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
  messages:
    basename: message/platform_core_err_message
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER_ADDR:localhost}:${MYSQL_SERVER_PORT:3306}/${MYSQL_SERVER_DATABASE_NAME:wecube_core}?serverTimezone=${TZ:Asia/Shanghai}&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false
    username: ${MYSQL_USER_NAME:db-user}
    password: ${MYSQL_USER_PASSWORD:db-password}
    hikari:
      pool-name: We3_HikariCP
      minimum-idle: 20
      idle-timeout: 180000
      maximum-pool-size: 200
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  banner:
    location: classpath:/banner.txt
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
camunda:
  bpm:
    enabled: true
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: false
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    history-level: full
    database:
      schema-update: true
    filter:
      create: All tasks
    job-execution:
      enabled: true
    auto-deployment-enabled: true
    generate-unique-process-application-name: true
    generate-unique-process-engine-name: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:mapper/plugin/*Mapper.xml,classpath*:mapper/workflow/*Mapper.xml
  type-aliases-package: com.webank.wecube.platform.core.entity
wecube:
  core:
    db-init-strategy: update
    gateway-url: 127.0.0.1:19110
    gateway-host-ports: 127.0.0.1:19110,127.0.0.1:19111
    httpclient:
      max-total-connections: 200
    authserver:
      host: 127.0.0.1
      port: 19110
    plugin:
      plugin-deploy-path: /opt
      plugin-package-bucket-name: wecube-plugin-package-bucket
      register-file: register.xml
      image-file: image.tar
      ui-file: ui.zip
      init-db-sql: init.sql
      upgrade-db-sql: upgrade.sql
      static-resource-server-ip: ${STATIC_RESOURCE_SERVER_IP:127.0.0.1}
      static-resource-server-user: ${STATIC_RESOURCE_SERVER_USER:user}
      static-resource-server-password: ${STATIC_RESOURCE_SERVER_PASSWORD:password}
      static-resource-server-port: ${STATIC_RESOURCE_SERVER_PORT:22}
      static-resource-server-path: ${STATIC_RESOURCE_SERVER_PATH:/root/app/ui-resources}
      base-mount-path: /data
      static-resource-server-auth-mode: ${STATIC_RESOURCE_SERVER_AUTH_MODE:PASSWD}
      static-resource-server-key-path: ${STATIC_RESOURCE_SERVER_KEY_PATH:/root/docker/cert/id_rsa}
    s3:
      endpoint: http://s3-server:9000
      access-key: s3-access-key
      secret-key: s3-secret-key
    resource:
      dockerPullImageTimeout: 300
      passwordEncryptionSeed: defaultSeed
    docker-remote:
      port: 2375
      enable-tls: false
      cert-path: /root/docker/cert
platform:
  auth:
    jwt-sso-authentication-uri: http://localhost:9090/auth/v1/api/login
    jwt-sso-access-token-uri: http://localhost:9090/auth/v1/api/token
    sub-system-code: SYS_PLATFORM
    sub-system-private-key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAwnTN7JDXFcSoikXuNOQDtAjic1Wu6oAtCQJquCJmXrBTqB7hwS2mK6TuT8P7Jx60BQcaRL12hPLi6cOiCawuVwIDAQABAkB9NORazDARjhzPW5OzbpWL2KSmiqcjywA0at/4S/4KPPM8vwRjzEMs7pV9nSJ2M+/YOqPMBDl8iBUSLpfKf/uxAiEA52UroIvo2URlmAycaJm7+e4QqqfhEnM9wlGCJwL2jTsCIQDXIh2zwN7KQEIypmOL+uXvlZUjmx0Tj29mWOwP/fBBlQIhAI9+VLSlror1eE73GxNeqoxNznYVz2RCpLzZEO4iT0S7AiARg0Z1tpKsVjTNWLwrzf3f1gZxApSIXhnMdBqrZpmjTQIhAJhgYctlaydmggTPCqWLGub9WqEyH2HrrcabRvpWdEcV
    auth-server-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKds8XUHglF0703p8H+IPQCTE+31A6t+eyTzF+6kHEpLp7YeDu7OZCqIH6pYWmxD0TmQLobjPNA7IME93wq8HX0CAwEAAQ==