server:
   port: 8080
   servlet:
      context-path: /auth
logging:
   config: classpath:logback-spring.xml
spring:
   datasource:
      url: jdbc:mysql://${MYSQL_SERVER_ADDR:localhost}:${MYSQL_SERVER_PORT:3306}/${MYSQL_SERVER_DATABASE_NAME:auth_server}?useUnicode=true&characterEncoding=UTF8&useJDBCTCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=${TZ:Asia/Shanghai}&useSSL=false
      username: ${MYSQL_USER_NAME:db_user}
      password: ${MYSQL_USER_PASSWORD:db_password}
      driver-class-name: com.mysql.cj.jdbc.Driver
   profiles:
      active: dev
   messages:
      basename: message/platform_auth_err_message
      encoding: UTF-8
   thymeleaf:
      cache: false
   jpa:
      database: mysql
      show-sql: false
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
   mvc:
      pathmatch:
         matching-strategy: ANT_PATH_MATCHER
         
platform:
   auth:
      server:
         db-init-strategy: update
         private-key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAp2zxdQeCUXTvTenwf4g9AJMT7fUDq357JPMX7qQcSkunth4O7s5kKogfqlhabEPROZAuhuM80DsgwT3fCrwdfQIDAQABAkAnM5IBteVkjz2s/5apNcwaw1VKRTE7yVyqFSVIYjKhjl5aA1ZcFwPx1Tue+kO5SXCR130x7gPA8t3sBjwwNWBBAiEA0ug/GxgrjTRI3jo+5Eojngm4zo15rQC5mm3fZLYvIY0CIQDLOMfOmE1jlciD8wd7cir6wqrDmRCUhAngbqBa9XtXsQIhALwF5MyI3brC0/uaPZtUJTCtRh6Ordz3+n+cWD321Um5AiANESuX1ycyvhDUmy3h/CdTVG0SgqcURaE08ygQcTRrIQIhAJO1gqZlPthg3t8y04XM+IY5Cmy9MHIgasmsI7HpvhGM
         public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKds8XUHglF0703p8H+IPQCTE+31A6t+eyTzF+6kHEpLp7YeDu7OZCqIH6pYWmxD0TmQLobjPNA7IME93wq8HX0CAwEAAQ==
         jwt-token:
            user-refresh-token: 30
            user-access-token: 10
            sub-system-refresh-token: 432000
            sub-system-access-token: 432000
   