server:
   port: 8080

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/wecube_cds?useUnicode=true&characterEncoding=UTF8&useJDBCTCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      ***REMOVED***
      driver-class-name: com.mysql.cj.jdbc.Driver